### ISSUE TITLE
`isArchivedRepo` broken on Global navigation update

### ISSUE THREAD

**Issue by fregante** [refined-github/github-url-detection#165]
No ".Label" element anymore, it only appears on the repo home

https://github.com/fregante/iphone-inline-video

```
📕 0.0.0 → TypeError: Cannot read properties of null (reading 'textContent')
    at Module.isArchivedRepo (refined-github.js:26029:90)
    at isArchivedRepoAsync (refined-github.js:18073:60)
    at async init (refined-github.js:12546:7)
    at async runFeature (refined-github.js:3797:16)
    at async setupPageLoad (refined-github.js:3809:5)
```

**Comment by fregante** [comment]
isPublicRepo was already fixed in https://github.com/refined-github/github-url-detection/pull/159
